---
title: "Código de Conduta"
output:
  html_document:
    keep_md: yes
---

R-Ladies tem como objetivo proporcionar uma experiência livre de assédio para todos. Não toleramos nenhuma forma de assédio aos participantes.

Este código de conduta aplica-se a todos os espaços R-Ladies, incluindo: meetups, Twitter, Slack, listas de discussão, tanto online como offline. Qualquer pessoa que viole este código de conduta pode ser advertida, punida ou expulsa destes espaços, conforme critérios dos Membros Fundadores.

Alguns espaços R-Ladies podem ter regras adicionais em vigor, que serão claramente disponibilizadas aos participantes. Os participantes são responsáveis por conhecer e respeitar estas regras.

**Entende-se como assédio:**

- Comentários ofensivos relacionados ao gênero, identidade e expressão de gênero, orientação sexual, deficiência, doença mental, neuro-atipicidade, aparência física, tamanho corporal, idade, raça ou religião.
- Comentários indesejáveis sobre as escolhas e práticas de estilo de vida, incluindo aquelas relacionadas com alimentos, saúde, parentalidade, drogas e emprego.
- Mal entendidos deliberados ou uso de nomes preconceituosos rejeitados ou "mortos".
- Imagens ou comportamentos sexuais gratuitos, ou fora do tópico em espaços inapropriados.
- Contato físico e contato físico simulado (por exemplo, descrições textuais como " abraço" ou "backrub") sem consentimento ou após um pedido para parar.
- Ameaças de violência.
- Incitação à violência contra qualquer indivíduo, incluindo incentivar uma pessoa a cometer suicídio ou praticar auto-agressão.
- Intimidação deliberada.
- Perseguição ou invasão de privacidade.
- Assédio à fotografia ou gravação, incluindo atividades de registro on-line para propósitos de assédio.
- Interrupção sustentada da discussão.
- Atenção sexual indesejável.
- Padrão de contato social inadequado, como solicitar / assumir níveis inadequados de intimidade com os outros.
- Continuação da comunicação um-a-um após os pedidos de cessação.
- Deliberar exposição de qualquer aspecto da identidade de uma pessoa sem o seu consentimento, exceto quando necessário para proteger as pessoas vulneráveis de abuso intencional.
- Publicação de comunicação privada não-assediante.

R-Ladies prioriza a segurança das pessoas "marginalizadas" em detrimento do conforto das pessoas privilegiadas. Os Membros Fundadores não agirão sobre reclamações relativas a:

- "Reversões", incluindo "racismo reverso", "sexismo inverso" e "cisfobia".
- A comunicação razoável de limites, como "deixe-me sozinho", "vá embora" ou "não estou discutindo isso com você".
- Comunicado em "tom" antipático.
- Críticas a comportamentos ou suposições racistas, sexistas, cissexistas ou de qualquer outra forma opressiva.

## Denúncias
Se você for assediado por um membro / convidado / participante de / em algum evento R-Ladies, ou ainda observe que alguém esteja sob assédio ou tem outras dúvidas, entre em contato com os Membros Fundadores através de reporting [at] rladies [dot] org. As incidências locais serão tratadas juntamente com os organizadores locais. Se a pessoa que está assediando você estiver na equipe, ela não participará da resolução do seu incidente. Responderemos o mais rápido possível.

Este código de conduta aplica-se aos espaços de eventos do R-Ladies. Mas, se você for assediado por um membro / convidado / participante em eventos do R-Ladies fora de nossos espaços, queremos saber sobre esse fato também. Levamos a sério todas as denúncias de assédio por parte de membros do R-Ladies, especialmente os membros fundadores. Isso inclui assédio fora de nossos espaços e assédios ocorridos a qualquer instante. Os membros fundadores se reservam o direito de excluir as pessoas do R-Ladies com base em seu comportamento passado, incluindo comportamento externo aos espaços R-Ladies e comportamento às pessoas externas ao R-Ladies.

A fim de proteger os voluntários de abuso e esgotamento ("burnout"), reservamo-nos o direito de rejeitar qualquer denúncia que acreditamos ter sido feita de má-fé. Denúncias destinadas a silenciar críticas legítimas podem ser excluídas sem resposta.

Respeitamos os pedidos de confidencialidade com o propósito de proteger as vítimas de abuso. A nosso critério, podemos publicamente nomear uma pessoa sobre quem recebemos queixas de assédio ou advertir privadamente a terceiros sobre os assediadores, se acreditarmos que isso aumentará a segurança dos membros da R-Ladies ou do público em geral. Não nomearemos vítimas de assédio sem seu consentimento afirmativo.

## Consequências
Espera-se que o comportamento assediador seja interrompido imediatamente quando pedido.

Se um participante se comporta como assediador, os membros fundadores podem tomar qualquer ação que julgarem apropriada, inclusive banimento do referido participante de todos os espaços do R-Ladies e identificação do participante para outros membros da comunidade R-Ladies ou o público em geral.

Esta política está licenciada sob a licença Creative Commons Zero.