baseURL = "https://rladies-dev.netlify.app/"
title = "R-Ladies Global"
theme = "hugo-rladies"
publishDir = "build"
ignoreFiles = ["\\.Rmd$","\\.qmd$", "_cache$", "\\.DS_Store", "_files$", 
  "content/post/\\*/index\\*\\.html", "_cache$", "README", "README_img/"]

pygmentsUseClasses = true
enableGitInfo = true
enableRobotsTXT= true

languageCode = "en"
defaultContentLanguage = "en"

#[outputs]
#  home = ["HTML", "RSS", "JSON"]
