title: "RLadies+ Global"
theme: "hugo-rladiesplus"
publishDir: "public"

languageCode: "en"
defaultContentLanguage: "en"
summaryLength: 30

pygmentsUseClasses: true
enableRobotsTXT: true
enableGitInfo: true
minify:
  minifyOutput: true

buildFuture: true
buildDrafts: false
timeout: "300s"

markup:
  goldmark:
    renderer:
      lazyLoadImages: true

taxonomies:
  category: categories
  tag: tags

ignoreLogs:
  - "warning-goldmark-raw-html"

ignoreFiles:
  - "\\.Rmd$"
  - "\\.qmd$"
  - "_cache$"
  - "\\.DS_Store"
  - "_files$"
  - "content/*/\\*/index\\*\\.html"
  - "README"
  - "README_img/"

outputFormats:
  Calendar:
    mediaType: text/calendar
    baseName: calendar
    isPlainText: true
    protocol: webcal://

outputs:
  home:
    - HTML
    - RSS
  section:
    - HTML
    - RSS
  page:
    - HTML
