main:
  - identifier: find
    url: "#"
    weight: 1
  - identifier: events
    url: /events/
    weight: 1
    parent: find
  - identifier: chapters
    url: /chapters/
    weight: 2
    parent: find
  - identifier: directory
    url: /directory/
    weight: 3
    parent: find

  - identifier: news
    url: /news/
    weight: 2

  - identifier: programs
    url: /programs/
    weight: 3

  - identifier: about-us
    url: "#"
    weight: 99
  - identifier: our-story
    url: /about-us/our-story/
    weight: 1
    parent: about-us
  - identifier: get-involved
    url: /about-us/involved/
    weight: 2
    parent: about-us
  - identifier: global-team
    url: /about-us/global-team/
    weight: 3
    parent: about-us
  - identifier: press
    url: /press
    weight: 5
    parent: about-us
