---
title: "Events"
output: html_document
slug: events
---


```{css, echo=FALSE}
/* for today circle */
  .tui-full-calendar-weekday-grid-date-decorator {
    background: #88398a !important;
  }

.button {
  background-color: #88398a;
    border: none;
  color: white;
  padding: 15px 25px;
  text-align: center;
  font-size: 16px;
  cursor: pointer;
}

.button:hover {
  background-color: #88398ab4;
}

.tui-calendar-today {
  background: #88398a !important;
}

```


```{r setup, include=FALSE}
# remotes::install_github("Athanasiamo/meetupr")
library(meetupr)
library(dplyr)

htmltools::tagList(rmarkdown::html_dependency_font_awesome())

rpurple <- "#88398a"
rgrey <- "#a7a9ac" 

# TODO find a better long-term solution than downloading everything 
# every time? Find a way to store csv of past events?, and just add 
# new, but then need a good way to "dump" past events into
# csv when they become "past". 

past_events <- read.table(paste0(here::here(),"/data/events.tsv"), 
                          sep = ";", header = TRUE, stringsAsFactors = FALSE)

new_events <- get_pro_events("rladies") %>% 
  mutate(type = "planned") 

  bind_rows(
    mutate(get_pro_events("rladies", "past"), type="past")
    ) %>%
  transmute(
    calendarId = chapter,
    title = name, 
    body = paste0(
      "<i class='fa fa-users'></i>&emsp;", yes_rsvp_count,
      "<br><br>",
      str_sub(description,1,300),
      "...  <br><br> <a href='", link, 
      "'><button class='button'>Event page</button></a>"),
    start = as.POSIXct(paste(local_date, local_time), format="%Y-%m-%d %H:%M"),
    # end = start,
    location = ifelse(
      is.na(venue_name), "Not announced",
      paste(venue_name, venue_address_1, venue_city, str_to_upper(venue_country), sep=", ")),
    category = "time",
    lat = venue_lat,
    lon = venue_lon,
    type = type
  ) %>%  
  as_tibble()

cals <- events %>% 
  transmute(
    name = calendarId,
    id = calendarId,
    color = "#FFF",
    bgColor = rpurple
  ) %>% 
  unique()
```
```{r month-theme, echo = FALSE}

# calendar month theme ----
theme_calendar_month <- list(
  
  common.border = paste0("1px solid ", rgrey, "80"),
  common.backgroundColor = "white",
  common.holiday.color = rpurple,
  common.saturday.color =rgrey,
  common.dayname.color = grey,
  common.today.color = rgrey,
  
  ## month header dayname
  month.dayname.height = "31px",
  month.dayname.borderLeft = paste0("1px solid ", rpurple, "FF"),
  month.dayname.paddingLeft = "10px",
  month.dayname.paddingRight = "10px",
  month.dayname.backgroundColor = paste0(rpurple, "64"),
  month.dayname.fontSize = "12px",
  month.dayname.fontWeight = "normal",
  month.dayname.textAlign = "left",
  
  ## month day grid cell day
  month.holidayExceptThisMonth.color = paste0(rpurple, "0A"),
  month.dayExceptThisMonth.color = paste0(rgrey, "b4"),
  month.weekend.backgroundColor = "inherit",
  month.day.fontSize = "14px",
  
  ## month schedule style
  month.schedule.borderRadius = "2px",
  month.schedule.height = "24px",
  month.schedule.marginTop = "2px",
  month.schedule.marginLeft = "8px",
  month.schedule.marginRight = "8px",
  
  ## month more view
  month.moreView.border = "1px solid #d5d5d5",
  month.moreView.boxShadow = "0 2px 6px 0 rgba(0, 0, 0, 0.1)",
  month.moreView.backgroundColor = "white",
  month.moreView.paddingBottom = "17px",
  month.moreViewTitle.height = "44px",
  month.moreViewTitle.marginBottom = "12px",
  month.moreViewTitle.backgroundColor = "inherit",
  month.moreViewTitle.borderBottom = "none",
  month.moreViewTitle.padding = "12px 17px 0 17px",
  month.moreViewList.padding = "0 17px"
)
```

```{r "calendar", echo=FALSE}
# remotes::install_github("dreamRs/tuicalendr")
library(tuicalendr)

calendar(
  defaultView = "month", useNav = TRUE, 
  useDetailPopup = TRUE, scheduleView = TRUE,
  bttnOpts = bttn_options(bg = rpurple, color = "#FFF")
) %>% 
  set_theme(theme_list = theme_calendar_month) %>% 
  set_calendars_props_df(cals) %>% 
  add_schedule_df(events)
```

```{r "leaflet", echo=FALSE, warning=FALSE, out.width='100%'}
library(leaflet)

sz <- c(31, 23)
events %>% 
  filter(type == "planned") %>% 
  leaflet() %>% 
  addTiles() %>% 
  addMarkers(lat= ~lat, lng= ~lon,
             popup = ~body, 
             label = ~calendarId, 
             icon = list(
               iconUrl = paste0(here::here(),"/static/images/marker.svg"),
               iconSize = sz,
               iconAnchorX = sz[2]/2, 
               iconAnchorY = sz[1]
             ),
             clusterOptions = markerClusterOptions())
```


```{r, include=FALSE}
# calendar week theme ----
theme_calendar_week <- list(
  
  ## week header dayname
  week.dayname.height = "42px",
  week.dayname.borderTop = paste0("1px solid ", rgrey, "80"),
  week.dayname.borderBottom = paste0("1px solid ", rgrey, "80"),
  week.dayname.borderLeft = "inherit",
  week.dayname.paddingLeft = "0",
  week.dayname.backgroundColor = "inherit",
  week.dayname.textAlign = "left",
  week.today.color = rgrey,
  week.pastDay.color = "#bbb",
  
  ## week vertical panel vpanel
  week.vpanelSplitter.border = paste0("1px solid ", rgrey, "80"),
  week.vpanelSplitter.height = "3px",
  
  ## week daygrid daygrid
  week.daygrid.borderRight = paste0("1px solid ", rgrey, "80"),
  week.daygrid.backgroundColor = "inherit",
  
  week.daygridLeft.width = "72px",
  week.daygridLeft.backgroundColor = "inherit",
  week.daygridLeft.paddingRight = "8px",
  week.daygridLeft.borderRight = paste0("1px solid ", rgrey, "80"),
  
  week.today.backgroundColor = paste0(rpurple, "0A"),
  week.weekend.backgroundColor = "inherit",
  
  ## week timegrid timegrid
  week.timegridLeft.width = "72px",
  week.timegridLeft.backgroundColor = "inherit",
  week.timegridLeft.borderRight = paste0("1px solid ", rgrey, "80"),
  week.timegridLeft.fontSize = "11px",
  week.timegridLeftTimezoneLabel.height = "40px",
  week.timegridLeftAdditionalTimezone.backgroundColor = "white",
  
  week.timegridOneHour.height = "52px",
  week.timegridHalfHour.height = "26px",
  week.timegridHalfHour.borderBottom = "none",
  week.timegridHorizontalLine.borderBottom = paste0("1px solid ", rgrey, "80"),
  
  week.timegrid.paddingRight = "8px",
  week.timegrid.borderRight = paste0("1px solid ", rgrey, "80"),
  week.timegridSchedule.borderRadius = "2px",
  week.timegridSchedule.paddingLeft = "2px",
  
  week.currentTime.color = paste(rpurple, "E6"),
  week.currentTime.fontSize = "11px",
  week.currentTime.fontWeight = "normal",
  
  week.pastTime.color = "#bbb",
  week.pastTime.fontWeight = "normal",
  
  week.futureTime.color = rgrey,
  week.futureTime.fontWeight = "normal",
  
  week.currentTimeLinePast.border = paste("1px solid ", rpurple),
  week.currentTimeLineBullet.backgroundColor = "inherit",
  week.currentTimeLineToday.border = paste("1px solid ", rpurple),
  week.currentTimeLineFuture.border = "none",
  
  ## week daygrid schedule style
  week.dayGridSchedule.borderRadius = "2px",
  week.dayGridSchedule.height = "24px",
  week.dayGridSchedule.marginTop = "2px",
  week.dayGridSchedule.marginLeft = "8px",
  week.dayGridSchedule.marginRight = "8px"
)
```


