---
title: "#VidasNegrasImportam: Uma declaração conjunta de Forwards e R-Ladies"
author: "R-Ladies Global Leadership Team"
date: "2020-06-06"
description: "#VidasNegrasImportam: Uma declaração conjunta de Forwards e R-Ladies"
tags: 
- social-justice
- portuguese
categories:
- r-ladies
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Como organizações comprometidas em ampliar a diversidade e a inclusão em nossa comunidade, apoiamos o movimento #BlackLivesMatter ou #VidasNegrasImportam e nos unimos a quem exige justiça frente a opressão sistêmica. O racismo generalizado afeta negativamente a participação das pessoas negras na sociedade. Os eventos atuais nos EUA ecoam o que aconteceu e continua acontecendo com pessoas que fazem parte de minorias em todo o mundo. Estamos agregando recursos e adotando ações deliberadas para amplificar as vozes de pessoas negras, indígenas e de outros grupos não-brancos da comunidade R, agora e no futuro.

Para as pessoas que compõem nossa comunidade e que estão sofrendo agora, gostaríamos de dizer que apoiamos vocês, ouvimos suas vozes, mas sabemos que isso não é suficiente para promover a mudança que precisamos. O trabalho de quebrar sistemas injustos é lento e difícil, e sabemos que algumas de vocês carregam mais carga do que outras. E não há palavras que tornem isso mais fácil.

## Uma mensagem da Forwards

A Forwards reconhece que as pessoas negras geralmente estão ausentes ou são negligenciadas nas principais atividades da comunidade R. Reconhecemos que muitas pessoas estão frustradas com o lento progresso ou a aparente falta de ação. Neste momento que nos lembra de que a injustiça racial oprime e impede o desenvolvimento das pessoas, é nosso objetivo criar espaço para que pessoas negras, indígenas e de outros grupos não-brancos ascendam como pessoas programadoras e líderes de comunidades.

Nós trabalhamos através de ações pequenas, mas esperamos que tenham impacto, tais como:

* Destacar o trabalho de pessoas de grupos sub-representados e compartilhar informações sobre eventos e oportunidades relevantes no [Twitter da @R_Forwards](https://twitter.com/r_forwards).

* Oferecer suporte às pessoas organizadoras da conferência useR! com o programa de bolsas de diversidade.

* Recomendar pessoas de grupos sub-representados para funções como palestrantes de conferências, membras de comitês, presidentas de sessão, etc.

* Apoiar a equipe de liderança da [AfricaR](https://africa-r.org/).

* Atingir um grupo diversificado com os nossos [Workshops para Mulheres e Meninas](https://forwards.github.io/blog/2019/09/22/workshops-for-women-and-girls/) e workshops em regiões insuficientemente servidas (ex. [Cuba](https://forwards.github.io/blog/2018/07/07/havanar/), [Southern Africa](https://forwards.github.io/blog/2020/05/25/southern-africa-project-2020/)).

Entendemos que muito mais poderia ser feito para apoiar e representar diretamente as pessoas negras, indígenas e de outros grupos não-brancos, e nos comprometemos a fazer nossa parte. Continuaremos a desenvolver ações e metas de longo prazo para melhorar a representação interseccional em nossa força-tarefa e na comunidade R em geral.

## Mensagem da R-Ladies

Como a missão da R-Ladies é focada em melhorar a diversidade de gênero na comunidade R, também reconhecemos a luta que as pessoas negras enfrentam e o efeito composto interseccional quando uma pessoa membra se identifica com vários grupos sub-representados. A R-Ladies Global se compromete a melhorar a forma como a organização apoia pessoas negras, indígenas e de outros grupos não-brancos através das seguintes ações:


* Iniciaremos e continuaremos o diálogo sobre ações concretas para promover a justiça social, globalmente, através de canais dedicados em nossos espaços de trabalho no Slack. À medida que nos engajamos, nos comprometemos a ouvir, sentir empatia, procurar entender e traduzir nossas conversas em ação. Nos comprometemos a tornar os espaços da nossa comunidade lugares que ofereçam não apenas segurança para todas as pessoas que a integram, mas também um trabalho ativo em prol da equidade e da justiça.

* Incorporaremos em nosso site uma página dedicada a recursos e informações sobre ações tangíveis que nós, como organização, e também como pessoas individuais, podemos adotar para apoiar o #BlackLivesMatter ou #VidasNegrasImportam e outros movimentos em prol da justiça social.

* Melhoraremos a diversidade da representação étnico-racial na Equipe Global da R-Ladies, para que as vozes de todas as minorias interseccionais sejam mais bem representadas. 

* Lançaremos uma série de programas para apoiar integrantes de nossa comunidade (por exemplo, bolsas de viagem, vouchers de livros, assinaturas educacionais) por meio de fundos doados a R-Ladies. Dedicaremos 50% dos fundos a pessoas membras da comunidade com identidades interseccionais, e metade disto direcionados exclusivamente para pessoas negras que fazem parte da comunidade.

## Declaração de encerramento


Nós trabalharemos mais para ouvir e amplificar as vozes de pessoas percententes a grupos minoritários de nossas respectivas comunidades em todo o mundo. Estamos engajadas no trabalho contínuo de romper sistemas injustos e em abrir espaço para que aquelas pessoas que atualmente sofrem nesses sistemas participem plenamente, e ocupem posições de liderança. Pedimos a todas as pessoas da comunidade R que façam o mesmo.


Time principal da R Forwards: Heather Turner, Noa Tamir, Tatjana Kecojevic, Emily Dodwell, Kevin O’Brien, Julie Josse.

R-Ladies Global: Claudia Vitolo, Erin LeDell, Hannah Frick, Laura Ación, Athanasia Monika Mowinckel, Yanina Bellini Saibene, Noa Tamir, Maëlle Salmon, Jennifer Thompson, Florencia D’Andrea, Patricia A. Loto, Saranjeet Kaur Bhogal, Christin Zasada, Nadejda Sero, Sheila Saia.

Pessoas organizadoras de capítulos R-Ladies (atuais e anteriores) com outras fortemente envolvidas nas comunidades R-Ladies e R: gwynn sturdevant, Paola Corrales, Paloma Rojas-Saunero, Riva Quiroga, Roxana Noelia Villafañe, Monica L. Alonso, Danielle Navarro, Mine Çetinkaya-Rundel, Sara Mortara, Genelle Denzin, Divya Seernani, Elisa Schneider, Kyla McConnel, Ana Laura Diedrichs, Liza Dosso, Mariel Lovatto, María Nanton, Ludmila Janda, Hazel Kavili, Ines Teacã, Lucía Rodríguez Planes, Andrea Sánchez-Tapia, Disha Patil, Ayanthi Gunawardana, Jan Strappa, Kaelen Medeiros, Vebashini Naidoo, Emily Dodwell, Julia Silge, Marcela Alfaro, Jenny Bryan, Lucy D’Agostino McGowan, Alison Hill, Andrea Gómez Vargas, Angela Li, Beatriz Milz, Haydee Svab, Tijana Blagojev, Katarina Kosmina, Jovana Savic.



> Tradução por Beatriz Milz, revisão por Haydee Svab, Monique Freitas e Regina Albanese.
