name: New chapter
description: Add a new R-Ladies chapter
title: "NEW CHAPTER: "
labels: ["chapter", "new"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting in a new chapter.
  - type: input
    id: country
    attributes:
      label: Chapter country
      description: Be dilligent in spelling.
      placeholder: ex. India
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: Chapter region/state/province
      description: Be dilligent in spelling.
      placeholder: ex. Eastern
    validations:
      required: false
  - type: input
    id: city
    attributes:
      label: Chapter city
      description: All chapters must be in a city. Be dilligent in spelling.
      placeholder: ex. New Dehli
    validations:
      required: true
  - type: textarea
    id: organizers
    attributes:
      label: Chapter organisers
      description: Please provide a comma-separated list of organisers, without quotes
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: Chapter status
      options:
        - prospective
        - active
        - retired
    validations:
      required: true
  - type: input
    id: some_meetup
    attributes:
      label: Meetup group name 
      placeholder: rladies/city
      description: Please only create this issue once meetup is initiated, this url is important for other website logistics.
    validations:
      required: true
  - type: input
    id: some_email
    attributes:
      label: Email 
      placeholder: chapter@rladies.org
    validations:
      required: true
  - type: input
    id: some_twitter
    attributes:
      label: twitter handle
      placeholder: '@rladies_city'
  - type: input
    id: some_mastodon
    attributes:
      label: Mastodon url handle
      placeholder: user@server.org
      