---
title: "#BlackLivesMatters : une déclaration commune de "Forwards" et "R-Ladies"
author: "R-Ladies Global Leadership Team"
date: "2020-06-06"
description: "#BlackLivesMatters : une déclaration commune de "Forwards" et "R-Ladies"
tags: 
- social-justice
categories:
- r-ladies
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

En tant qu'organisations dédiées à augmenter la diversité et
l'intégration de tous dans nos communautés, nous soutenons #BlackLivesMatter et rejoignons ceux qui demandent justice face à
l'oppression systémique. Le racisme omniprésent affecte négativement la participation
de personnes noires dans notre société. Les événements en cours aux États-Unis font écho à ce qui s'est produit et continue de se produire pour les personnes marginalisées (ou réduites à être des minorités) à travers le monde. 
Nous rassemblons des ressources et prenons des mesures pour amplifier la
voix des personnes noires, indigènes et de couleur dans la communauté R
maintenant et dans le futur.

Aux membres de notre communauté qui souffrent actuellement, nous
sommes à vos côtés, nous entendons vos voix, mais nous savons que cela
ne suffit pas pour provoquer le changement dont nous avons
besoin. Le travail visant à briser les systèmes d'injustice est lent et difficile, et nous savons que certain·e·s d'entre vous portent un peu plus le fardeau que d'autres. Il n'y a pas de mots pour rendre ceci plus facile ou léger.

## Un message de Forwards :

Forwards reconnaît que les personnes noires sont souvent absentes ou
négligées dans les activités principales de la communauté R. Nous
reconnaissons que beaucoup sont déçus par le progrès lent ou l'absence
d'action apparente. À un moment où l'actualité nous rappelle que l'injustice raciale tire les gens vers le bas, c'est notre rôle de
créer un espace pour les personnes noires, indigènes et de couleur
afin de développer leurs talents en tant que programmeurs en R et leaders communautaires.

Nous travaillons à travers de petites actions, qui nous espérons ont un impact, telles que :

- Mettre en valeur le travail de personnes de groupes sous-représentés
et partager des informations sur des événements clés et des opportunités
sur [\@R_Forwards Twitter](https://twitter.com/r_forwards).

- Soutenir les organisateurs de la conference useR! avec le programme de bourses pour la diversité

- Recommander des personnes de groupes sous-représentés pour des rôles
tels que conférenciers, membres de comités, président de séances,
etc.

- Soutenir l'équipe organisatrice de [AfricaR](https://africa-r.org/).

- Atteindre un groupe diversifié avec nos [ateliers pour femmes et
filles](https://forwards.github.io/blog/2019/09/22/workshops-for-women-and-girls/)
et ateliers dans des régions mal desservies (par exemple
[Cuba](https://forwards.github.io/blog/2018/07/07/havanar/), [le Sud de l'Afrique](https://forwards.github.io/blog/2020/05/25/southern-africa-project-2020/)).

Nous comprenons qu'il y aurait beaucoup plus à faire pour soutenir et
représenter directement les personnes noires, indigènes et de couleur
et nous sommes engagés à faire notre part. Nous continuerons à
développer des actions et des objectifs à long terme pour améliorer la
représentation intersectionelle dans notre groupe de travail et dans la grande communauté R.

## Un message de R-ladies :

Bien que la mission des R-Ladies se concentre sur l'amélioration de la diversité du genre au sein de la communauté R, nous reconnaissons également à la fois les difficultés auxquelles les personnes noires font face, et l'effet combiné de l'intersectionnalité lorsqu'un membre s'identifie à plusieurs groupes sous-représentés. R-Ladies Global s'engage à améliorer comment l'organisation soutient les
personnes noires, indigènes et de couleur à travers les actions suivantes :

- Nous entamerons et continuerons le dialogue autour d'actions
concrètes pour promouvoir la justice sociale partout dans le monde via des chaînes y dédiées dans nos espaces de travail Slack.
Nous nous engageons à écouter,
faire preuve d'empathie et chercher à comprendre et transformer nos
discussions en action. Nous nous engageons à faire de nos espaces communautaires
des endroits non seulement sûrs pour tous nos membres, mais aussi
d'espace de travail pour plus d'équité et de justice.

- Nous intégrerons à notre site web une page dédiée aux ressources et informations concernant les actions tangibles ou concrètes que nous, en tant qu'organisation, et en tant qu'individus pouvons entreprendre pour soutenir #BlackLivesMatter et d'autres mouvements pour la justice sociale.

- Nous améliorerons la représentation ethnique et raciale au sein de l'équipe organisatrice de R-ladies Global afin que les voix de toutes les minorités intersectionnelles soient mieux représentées.

- Nous lancerons un certain nombre de programmes pour soutenir nos membres (par exemple des bourses de voyage, des bons pour des livres, des inscriptions pédagogiques ou abonnements éducatifs) grâce aux ressources financières données à R-Ladies, nous consacrerons 50% de ces financements aux membres de la communauté avec des identités intersectionnelles et la moitié de ceux-ci seront destinés exclusivement aux membres noirs.

## Déclaration finale

Nous travaillerons plus dur ou intensivement pour écouter et amplifier les voix des membres issus de minorités de nos communautés respectives partout dans le monde entier.
Nous sommes investi·e·s dans le travail permanent et continu de briser les systèmes d'injustice; et de faire en sorte que ceux qui souffrent actuellement à cause de ces systèmes participent pleinement et occupent des postes de
responsabilité. Nous invitons, pressons chacun dans la communauté R à faire de même.

Équipe principale de Forwards : Heather Turner, Noa Tamir, Tatjana
Kecojevic, Emily Dodwell, Kevin O’Brien, Julie Josse.

Équipe de R-Ladies Global : Claudia Vitolo, Erin LeDell, Hannah Frick, Laura Ación, Athanasia Monika Mowinckel, Yanina Bellini Saibene, Noa Tamir, Maëlle Salmon, Jennifer Thompson, Florencia D’Andrea, Patricia A. Loto, Saranjeet Kaur Bhogal, Christin Zasada, Nadejda Sero, Sheila Saia. 

Organisatrices (actuelles et passées) d'antennes locales de R-Ladies et
autres fortement impliquées dans R-ladies et dans les communautés
R-Ladies: gwynn sturdevant, Paola Corrales, Paloma Rojas-Saunero, Riva Quiroga, Roxana Noelia Villafañe, Monica L. Alonso, Danielle Navarro, Mine Çetinkaya-Rundel, Sara Mortara, Genelle Denzin, Divya Seernani, Elisa Schneider, Kyla McConnel, Ana Laura Diedrichs, Liza Dosso, Mariel Lovatto, María Nanton, Ludmila Janda, Hazel Kavili, Ines Teacã, Lucía Rodríguez Planes, Andrea Sánchez-Tapia, Disha Patil, Ayanthi Gunawardana, Jan Strappa, Kaelen Medeiros, Vebashini Naidoo, Emily Dodwell, Julia Silge, Marcela Alfaro, Jenny Bryan, Lucy D’Agostino McGowan, Alison Hill, Andrea Gómez Vargas, Angela Li, Beatriz Milz, Haydée Svab, Tijana Blagojev, Katarina Kosmina, Jovana Savic.
