---
title: "Cómo hacer una reunión virtual inolvidable (sin morir en el intento)"
author: "Laura Ación, Yanina Bellini Saibene, Paola Corrales, Patricia Loto y Paloma Rojas"
date: "2020-06-02"
description: ""
tags:
- 2020
- spanish
categories:
- R-Ladies
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Versión corta

💻 **¿Qué?** 
Webinario en español gratuito para que cualquier evento virtual interactivo sea un éxito sin estrés adicional

🗓️ ⏰ **¿Cuándo?** 
Viernes 12 de Junio de 5 pm a 6 pm UTC (o en diferido vía grabación en YouTube)

✍️ **¿Cómo?**
Inscríbete vía meetup.com en el capítulo de R-Ladies hispanohablante más cercano que ofrezca el evento en los próximos días (links disponibles más abajo en este post)

### Versión larga

R-Ladies lleva adelante muchas actividades e iniciativas, pero su corazón son los capítulos alrededor del mundo donde la comunidad se reúne para aprender, enseñar y acompañarse. Desde la aparición del COVID19, los eventos presenciales fueron suspendidos, pero la magia de R-Ladies no se detiene y hace posible los encuentros virtuales. 

Iniciada la pandemia, el equipo de R-Ladies Global generó la infraestructura necesaria para que todos nuestros capítulos puedan realizar eventos virtuales (más información [en este post](https://blog.rladies.org/post/online-meetups) y poder difundirlos [desde YouTube](https://www.youtube.com/channel/UCDgj5-mFohWZ5irWSFMFcng).  Este es un paso necesario, pero no suficiente ya que muchas personas no tienen suficiente experiencia en la organización de eventos virtuales, en el dictado de clases y talleres online, o en la realización de videoconferencias. Por eso el segundo paso desde el equipo de R-Ladies Global es facilitar la formación en estos temas.  

Por todo lo anterior, organizamos **“Cómo hacer una reunión virtual inolvidable (sin morir en el intento)”**. En este webinario mostraremos algunos trucos y herramientas para que cualquier evento virtual interactivo (por ejemplo, clase, taller o panel online) sea un éxito sin estrés adicional al hacerlo. Si organizas meetups de R-Ladies, encontrarás dónde y cómo acceder a la infraestructura que te permitirá organizar meetups online para tu capítulo. Si no organizas meetups de R-Ladies, también encontrarás material útil para todo tipo de evento online que organices o del que participes.

Este es el primer evento online impulsado desde R-Ladies Global y también el primero para la comunidad internacional hispanohablante. Esperamos que sea el primero de muchos en muchos otros idiomas. 

Este webinario está organizado por R-Ladies latinoamericanas, en su mayoría certificadas para enseñar por RStudio Education y The Carpentries. La mayoría también es parte de MetaDocencia, una organización que desde fines de marzo realizó más de 25 talleres interactivos enseñando a enseñar online a más de 300 docentes hispanohablantes con excelentes resultados. Todas tienen vasta experiencia teletrabajando y enseñando online.

Para participar de este evento, tendrás que ingresar a la página de meetup.com de tu capítulo hispanohablante más cercano y dar RSVP al evento. El día antes del webinario, recibirás el link para escucharlo en vivo el 12 de Junio de 4 pm a 5 pm UTC. 

En los próximos días estos capítulos anunciarán el evento y te darán instrucciones para unirte a la transmisión en vivo: 

* [R-Ladies Barcelona, España](http://www.meetup.com/rladies-barcelona)    :flag-es:

* [R-Ladies Bariloche, Argentina](https://www.meetup.com/rladies-bariloche) :flag-ar: 

* [R-Ladies Buenos Aires, Argentina](https://www.meetup.com/rladies-buenos-aires) :flag-ar: 

* [R-Ladies Córdoba, Argentina](https://www.meetup.com/rladies-cordoba) :flag-ar: 

* [R-Ladies Cusco, Perú](https://www.meetup.com/rladies-cusco)  :flag-pe: 

* [R-Ladies Monterrey, México](https://www.meetup.com/rladies-monterrey) :flag-mx:

* [R-Ladies Montevideo, Uruguay](https://www.meetup.com/rladies-montevideo) :flag-uy: 

* [R-Ladies Puebla, México](https://www.meetup.com/rladies-puebla)   :flag-mx:

* [R-Ladies Querétaro, México](https://www.meetup.com/rladies-queretaro)   :flag-mx:

* [R-Ladies San José, Costa Rica](https://www.meetup.com/rladies-san-jose) :flag-cr: 

* [R-Ladies Santa Rosa, Argentina](https://www.meetup.com/rladies-santa-rosa)  :flag-ar: 

* [R-Ladies Santiago, Chile](https://www.meetup.com/rladies-scl) :flag-cl:

* [R-Ladies Ushuaia, Argentina](https://www.meetup.com/rladies-ushuaia)  :flag-ar: 

* [R-Ladies Valparaíso, Chile](https://www.meetup.com/rladies-valparaiso)  :flag-cl:

* [R-Ladies Resistencia-Corrientes, Argentina](https://www.meetup.com/rladies-resistencia-corrientes)  :flag-ar:


Si no puedes verlo en vivo, la grabación quedará disponible en nuestro canal de [YouTube](https://www.youtube.com/channel/UCDgj5-mFohWZ5irWSFMFcng) unos días más tarde, cuando lo hayamos subtitulado en español e inglés. 
 
En momentos como estos, la comunidad de R-Ladies muestra su valor más que nunca, dándonos la posibilidad de apoyarnos y ayudarnos para que podamos estar cerca, a pesar de la distancia social necesaria, y sigamos aprendiendo, creciendo y compartiendo.
