---
title: "@WeAreRLadies"
output: html_document
slug: rocur
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, echo = FALSE)
```

```{css 'css', echo = FALSE}
button{
  background-color: #88398a;
  border-radius: 1em;
  border: none;
  color: white;
  padding: 15px 32px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 4px 2px;
  cursor: pointer;
}

button:hover {
  background-color: #88398aee;
}
```

<div style='text-align: center;'>
### The R-Ladies RoCur
</div>

## About  

The **[R-Ladies RoCur (Rotating Curation)](https://twitter.com/WeAreRLadies)** is a twitter handle that will feature an awesome R-Lady each week. This account is run by R-Ladies Global.      
  
   
## Objectives  
  
1. To encourage and maintain Twitter engagement within the R-Ladies community.    
2. To spotlight female and minority genders (including but not limited to cis/trans women, trans men, non-binary, genderqueer, agender) and their great work in R.   
  
## How It Works  
  
Every week, a different R-Lady takes over our twitter account to talk about the work they do in R. Featured curators come from a diversity of professions and have a range of experiences in R, from novice to expert.  
  
If you are interested in becoming a curator, see our *Be a Curator* section (below) and [sign up here](https://goo.gl/forms/bQ7mHQDXrNHXEZCl2).  
  
Check out [@WeAreRLadies](https://twitter.com/WeAreRLadies) every Monday for a new curator!    
  
And [see the current curator schedule](https://docs.google.com/spreadsheets/d/1pmphnR9EinGuAKbVqGzMIt6cWYmHNbeFVzaKJB59JdY/edit?usp=sharing)  

***  
  
  
## Be a Curator! 
  
We are always looking for R-users to be a featured curator for our account! Everyone is welcome; R-Ladies encourages R-users of all professional backgrounds and experience levels to curate this account. Additionally, individuals do not need to be affiliated with R-Ladies to curate. Featured curators must meet the following criteria:  
  
* Curators must identify as female or non-binary.  
* Curators do not need to be affiliated with R-Ladies; however, curators need to register in the [R-Ladies directory](https://rladies.org/directory/) if they haven’t yet.   
* Curators must be individuals (i.e. an R-Ladies Chapter cannot be a featured curator; however, an organizer from a local chapter may curate and tweet about chapter events).   
* By signing on to be a curator of @WeAreRLadies you agree to our Curator Agreement that is outlined in our [RoCur Curator Guide](https://github.com/katherinesimeon/starter-kit/blob/master/RoCur-Twitter/files/RLadies-Rocur-Guide.md).    
  
## Curator Sign Up  
  
* They will be asked to provide a first and second choice.    
* Curatorship begins each Monday at 7:00 AM ET and ends the following Saturday at 12:00 PM ET.   
* Administrators will make all efforts to honor all scheduling requests but may ask that you be flexible as the administrators need to coordinate multiple schedules.  
* Administrators will contact you to schedule the week you will curate.  
  
<a href='https://goo.gl/forms/bQ7mHQDXrNHXEZCl2'><button type="button">Sign up to be a curator!</button></a>
   
## Contact Us  
  
This RoCur is managed by R-Ladies Global members. You can email us at WeAre@rladies.org or at the **#rocur_twitter** channel on the [R-Ladies Community Slack](https://rladies-community-slack.herokuapp.com/).  
  