---
title: "Community Slack"
output: html_document
slug: community-slack
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, echo = FALSE)
```

```{css 'css', echo = FALSE}
button{
  background-color: #88398a;
  border-radius: 1em;
  border: none;
  color: white;
  padding: 1.2em;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 1em .5em;
  cursor: pointer;
}

button:hover {
  background-color: #88398aee;
}
```


The Community Slack is intended for people that identify as a woman or gender minority and are interested in the R programming language.
It is a friendly and welcoming community, where you can share information, learn new things and connect with other R-Ladies.
The Community Slack is intended to be a harassment-free experience for everyone and the [Code of Conduct](coc/) is enforced to make sure everyone can enjoy the space.

<div style='text-align:center;'>
<a href=' http://rladies-community-slack.herokuapp.com'><button type="button">Join the community slack!</button></a>  
</div>

---

## Contact
If you have a question regarding R-Ladies community slack please contact slack [at] rladies.org.

If you would like to report harassment or violation of parts of the Code of Conduct, please contact reporting [at] rladies.org.

Within Slack you can contact us via "@Community Management Team".