---
title: "Meet the global team"
output:
  html_document:
    keep_md: yes
slug: global-team
type: "about-us"
---

```{css 'css', echo = FALSE}
.grid {
  display: flex;
  flex-wrap: wrap; 
  flex-direction: row;
  align-items: center;
  justify-content: center;
  width: 100%;
  list-style-type: none;
  overflow: wrap;
}

.grid-item {
  flex-grow: 1 0 0; 
  height: 200px;
  width: 200px;
}

.content {
  position: relative;
  height: 175px;
  width: 175px;
  border-radius: 1em;
  border: 1px solid #88398a;
  background-size: cover;
  -moz-transition: all 1s ease-in-out 0s;
	-webkit-transition: all 1s ease-in-out 0s;
	-ms-transition: all 1s ease-in-out 0s;
	transition: all 1s ease-in-out 0s;
}

.content-text{
  opacity: 0;
  width: 100%;
  height: 100%;
}

.content-text:hover {
  opacity: 1;
}

.content-text h1 {
  position: absolute;
  width: 100%;
  top: -23px;
  font-size: 14px;
  font-weight: 300;
  color: #fff;
  background-color: #88398abe;
  border-top-left-radius: 1em;
  border-top-right-radius: 1em;
  padding: 5px; 
  padding-left: 8px;

}

.content-text p {
  position: absolute;
  bottom: -31px;
  font-size: 12px;
  font-weight: 300;
  width: 100%;
  background-color: #ffffffde;
  border-bottom-left-radius: 1em;
  border-bottom-right-radius: 1em;
  color: #88398a;
  padding: 4px; 
  padding-left: 8px;
}



@media only screen and (max-width: 600px) {
  .card {
    width: 100%;
  }
}

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)

library(dplyr)
library(kableExtra)
library(tidyr)

make_square <- function(image, name, role){
  cat('<li>',
      '<div class="grid-item">',
      '<div class="content" style="background-image: url(', image, ');">',
      '<div class="content-text">',
      '<h1>', name, '</h1>',
      '<p>', gsub(",", "<br>", role), '<br></p>',
      '</div></div></div>',
      '</li>', sep="") 
}

fix_order <- function(x){
  j <- unique(c("Leadership Team",
                unique(x)[order(unique(x))]))
  
  factor(x, levels = j)
}

add_image <- function(img_path){

  image = file.path("img", img_path)
  
  # check if image is in static images
  if(file.exists(image)){
    return(image)
  }else{
    return("img/placeholder.png")
  }
}
```

```{r parse, include=FALSE}
team <- 'https://raw.githubusercontent.com/rladies/starter-kit/master/global-team.csv' %>% 
  readr::read_csv(trim_ws = TRUE) %>% 
  mutate(image = sapply(img, add_image))

leadership <- filter(team, role == "Leadership Team")
team <- filter(team, role != "Leadership Team")
```

## Leadership team

```{r 'leadership-table', echo=F}
leadership %>% 
  select(role, name) %>% 
  arrange(role, name) %>% 
  kable(align = "rl") %>%
  kable_styling(full_width = F) %>%
  column_spec(2, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```

<ul class="grid">
```{r leadership-img-grid, results='asis', echo = FALSE}
j <- mapply(make_square,
       name = leadership$name,
       role = leadership$role,
       image = leadership$image)
```
</ul>

---

## Global team

```{r 'team-table', echo=F}
team %>% 
  separate_rows(role, sep="; ") %>% 
  mutate(role = gsub("^ | $", "", role),
         role = fix_order(role)
         ) %>% 
  select(role, name) %>% 
  arrange(role, name) %>% 
  kable(align = "rl") %>%
  kable_styling(full_width = F) %>%
  column_spec(2, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```

<ul class="grid">
```{r team-img-grid, results='asis', echo = FALSE}
j <- mapply(make_square,
       name = team$name,
       role = team$role,
       image = team$image)
```
</ul>


---
## Former global team members

```{r 'former', echo=F}
former <- 'https://raw.githubusercontent.com/rladies/starter-kit/master/global-team-alumni.csv' %>% 
  readr::read_csv(trim_ws = TRUE, col_types = readr::cols()) %>% 
  mutate(image = sapply(img, add_image),
         period = paste(start, "-", end)) %>% 
  arrange(start, role, name)

former %>% 
  select(role, name, period) %>% 
  kable(align = "rll") %>%
  kable_styling(full_width = F) %>%
  column_spec(2, bold = T) %>%
  collapse_rows(columns = 1:2, valign = "top")
```


<ul class="grid">
```{r former-img-grid, results='asis', echo = FALSE}
j <- mapply(make_square,
       name = former$name,
       role = former$period,
       image = former$image)
```
</ul>