<!DOCTYPE html>
<html lang="en-us">
    <head>
         
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>R-Ladies IWD2018 tweets analysis, using the rtweet package</title>
        <style>

    html body {
        font-family: 'Open Sans', sans-serif;
        background-color: white;
    }

    :root {
        --accent: #88398A;
        --border-width:  5px ;
    }

</style>


<link rel="stylesheet" href="../../css/main.css">





<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open%20Sans">


 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/solarized-dark.min.css"> 


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
 


    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>

     <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/python.min.js"></script>  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/bash.min.js"></script> 

    <script>hljs.initHighlightingOnLoad();</script>







<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


<script>$(document).on('click', function() { $('.collapse').collapse('hide'); })</script>
 <meta name="generator" content="Hugo 0.37" />
        

        
    </head>

    
    
    <script type="text/javascript" async
      src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
    </script>
    

    <body>
         
        <nav class="navbar navbar-default navbar-fixed-top">

            <div class="container">

                <div class="navbar-header">

                    <a class="navbar-brand visible-xs" href="#">R-Ladies IWD2018 tweets analysis, using the rtweet package</a>

                    <button class="navbar-toggle" data-target=".navbar-collapse" data-toggle="collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                </div>

                <div class="collapse navbar-collapse">

                    
                        <ul class="nav navbar-nav">
                            
                                <li><a href="https://rladies.org/">Home</a></li>
                            
                                <li><a href="../../post/">Posts</a></li>
                            
                        </ul>
                    

                    
                        <ul class="nav navbar-nav navbar-right">
                            
                                <li class="navbar-icon"><a href="mailto:info@rladies.org"><i class="fa fa-envelope-o"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://github.com/rladies/"><i class="fa fa-github"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://twitter.com/RLadiesGlobal/"><i class="fa fa-twitter"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.meetup.com/es-ES/topics/r-ladies/all/"><i class="fa fa-meetup"></i></a></li>
                            
                                <li class="navbar-icon"><a href="https://www.linkedin.com/company/17981653/"><i class="fa fa-linkedin"></i></a></li>
                            
                        </ul>
                    

                </div>

            </div>

        </nav>


<main>

    <div class="item">

    
    
    

    
    

    <h3><a href="../../post/rladies_tweets/">R-Ladies IWD2018 tweets analysis, using the rtweet package</a></h4>
    <h5>April 17, 2018</h5>
    

</div>


    <br> <div class="text-justify post__main-text"><script src="../../rmarkdown-libs/htmlwidgets/htmlwidgets.js"></script>
<script src="../../rmarkdown-libs/d3/d3.min.js"></script>
<script src="../../rmarkdown-libs/d3-lasso/d3-lasso.min.js"></script>
<link href="../../rmarkdown-libs/ggiraph/styles.css" rel="stylesheet" />
<script src="../../rmarkdown-libs/ggiraph/ggiraph_utils.js"></script>
<script src="../../rmarkdown-libs/ggiraph/ggiraph_over_effect.js"></script>
<script src="../../rmarkdown-libs/ggiraph/ggiraph_zoom.js"></script>
<script src="../../rmarkdown-libs/ggiraph/ggiraph_tooltip.js"></script>
<script src="../../rmarkdown-libs/ggiraph/ggiraph_selector.js"></script>
<script src="../../rmarkdown-libs/ggiraph-binding/ggiraph.js"></script>
<script src="../../rmarkdown-libs/svg_1/scripts_svg_1.js"></script>


<p><a href="http://rladies.org/">R-Ladies</a> is a global organization that promotes diversity in the R community. One way to do this is by raising the visibility of women and other underrepresented genders<sup>1</sup> in tech, especially those who are R users, or developers.</p>
<hr />
<p><sup>1</sup> (cis/trans women, trans men, non-binary, genderqueer, agender, or other).</p>
<hr />
<p>The R-Ladies Global Team instigated a unique initiative to increase female visibility in tech, as part of the 2018 International Women’s Day celebration. They created a twitter account (@<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a>) to post - tweet by tweet- each profile of R-Ladies listed in the <a href="https://rladies.org/directory/">R-Ladies Global Directory</a>. For details on how they set up this initiative, check out <a href="http://blog.rladies.org/post/ideation_and_creation/">this</a> blog post.</p>
<p>Encouraged by the R-Ladies Global Team, but also out of simple curiosity, I decided to analyze these tweets and their interactions, using <a href="https://twitter.com/kearneymw">Mike Kearney’s</a> super useful <a href="https://github.com/mkearney/rtweet">rtweet</a> package.</p>
<div id="warnings" class="section level2">
<h2>Warnings</h2>
<p><strong>WARNING 1</strong>: The <code>rtweet</code> package interacts with Twitter’s API, which has a time limit of 7 days of doing it for free. If you would like to perform Twitter analyses after one week of tweets being created, you may have to <a href="https://developer.twitter.com/en/pricing">pay for this service</a>. The exception is when using <code>get_timeline</code>, but there is still a limit on the number of tweets you can fetch. It works for @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> because the account has relatively few tweets (n = 442 at the time of this analysis).</p>
<p><strong>WARNING 2</strong>: The Twitter API changes frequently. Therefore, the variable names I used for this analysis might change in the future. There should be similar variables being included in the API at any time, though. So if you want to use this code, make sure that you have up-to-date Twitter API variable names, and change anything if needed.</p>
</div>
<div id="the-game" class="section level2">
<h2>The game</h2>
<p>Apart from the initiative itself, the R-Ladies Global Team also created a game, where anybody could reply to each tweet with the Twitter handle of the featured R-Lady. The person with the largest amount of replies wins the game!</p>
<p><a href="https://twitter.com/rladies_iwd2018/status/971453057178402817"><img src="../../image/rladies_twitter.png" alt="R-Ladies Game" /></a></p>
</div>
<div id="resources" class="section level2">
<h2>Resources</h2>
<p>I used several resources for my analysis, including:</p>
<ul>
<li><a href="http://rtweet.info/articles/auth.html">How to create a Twitter App</a>: I used this article to set up a twitter app that could interact with the Twitter API using the <code>rtweet</code> package.</li>
<li><a href="http://rtweet.info/index.html">The <code>rtweet</code> package</a>: I used this webpage to understand the Twitter API, as per <code>rtweet</code>.</li>
<li><a href="https://mkearney.github.io/nicar_tworkshop/#1">Mike Kearney’s slides about <code>rtweet</code></a>: I used these slides as reference for the <code>search_tweets()</code> function.</li>
<li><a href="http://www.masalmon.eu/2017/12/05/badderb/">Maëlle’s blog post: “Names of b…..s badder than Taylor Swift, a class in women’s studies?”</a>: Another reference for <code>search_tweets()</code>.</li>
<li><a href="http://www.masalmon.eu/2017/02/28/rbloggerstweets/">Maëlle’s blog post: “A glance at R-bloggers Twitter feed”</a>: With this blog post, I learned how to explore the time at which tweets were posted, as well as some exploration about favorites and retweets.</li>
<li><a href="http://livefreeordichotomize.com/2017/07/24/twitter-trees/">Lucy’s blog post: Twitter tress</a>: The last bits of this blog post (about the replies tree) are based on this blog post.</li>
</ul>
</div>
<div id="questions" class="section level2">
<h2>Questions</h2>
<p>I had several questions at the beginning of this analysis:</p>
<ul>
<li>When were most of the tweets posted?</li>
<li>Is there any correlation between favorites and retweets?</li>
<li>What’s the location of the majority of tweets?</li>
<li>Who won the game?</li>
<li>What does the largest chain of tweets and replies look like?</li>
</ul>
</div>
<div id="load-packages" class="section level2">
<h2>Load packages</h2>
<pre class="r"><code>library(rtweet)
library(gridExtra)
library(dplyr)
library(lubridate)
library(ggplot2)
library(ggraph)
library(igraph)
library(ggiraph)</code></pre>
</div>
<div id="get-timeline-and-tweets" class="section level2">
<h2>Get timeline and tweets</h2>
<p>At the time of this analysis, the @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> twitter account has fewer than 500 tweets, so we can import all tweets by doing this:</p>
<pre class="r"><code>rladies_tweets &lt;- get_timeline(&quot;rladies_iwd2018&quot;, n = 500)</code></pre>
</div>
<div id="when-were-most-of-the-tweets-posted" class="section level2">
<h2>When were most of the tweets posted?</h2>
<p>International Women’s Day 2018 took place on March 8th, 2018. I’m assuming that most tweets came out on that day, but let’s check. Also, some of the replies were still being made a few days later.</p>
<pre class="r"><code>rladies_tweets &lt;- mutate(rladies_tweets, 
                         wday = as.factor(wday(created_at, 
                                               label = TRUE)))
rladies_tweets &lt;- mutate(rladies_tweets, 
                         hour = as.factor(hour(created_at)))
rladies_tweets &lt;- mutate(rladies_tweets, 
                         week = week(created_at))
rladies_tweets &lt;- mutate(rladies_tweets, 
                         day = as.Date(created_at))

weekday_dat &lt;- rladies_tweets %&gt;%
  group_by(week, wday) %&gt;%
  summarize(n = n(), created_at = created_at[1]) 

arrange(weekday_dat, created_at) %&gt;%
  head() %&gt;%
  knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">week</th>
<th align="left">wday</th>
<th align="right">n</th>
<th align="left">created_at</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">10</td>
<td align="left">Tue</td>
<td align="right">4</td>
<td align="left">2018-03-06 22:49:37</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">Wed</td>
<td align="right">106</td>
<td align="left">2018-03-07 23:58:56</td>
</tr>
<tr class="odd">
<td align="right">10</td>
<td align="left">Thu</td>
<td align="right">232</td>
<td align="left">2018-03-08 23:56:17</td>
</tr>
<tr class="even">
<td align="right">10</td>
<td align="left">Fri</td>
<td align="right">100</td>
<td align="left">2018-03-09 11:37:53</td>
</tr>
</tbody>
</table>
<p>Unsurprisingly, most tweets were posted on International Women’s Day!</p>
<p>In fact, all tweets were sent on International Women’s Day 2018, but because there are different time zones around the world, we get the impression that there were some tweets posted one day before and one day after. The table shows how I experienced tweets in my time zone (GMT +1), but all these timepoints correspond to International Women’s Day somewhere on Earth.</p>
</div>
<div id="is-there-any-correlation-between-favorites-and-retweets" class="section level2">
<h2>Is there any correlation between favorites and retweets?</h2>
<p>I took a look at the proportion of favorites and the proportion of retweets, and they are quite dissimilar:</p>
<pre class="r"><code>sum(rladies_tweets$favorite_count != 0) / 
  length(rladies_tweets$favorite_count)</code></pre>
<pre><code>## [1] 0.9954751</code></pre>
<pre class="r"><code>sum(rladies_tweets$retweet_count != 0) / 
  length(rladies_tweets$retweet_count)</code></pre>
<pre><code>## [1] 0.2737557</code></pre>
<p>So 99.5% of the @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> tweets have been favorited, but only 27.4% have been retweeted 🤔.</p>
<p>Let’s take a look at the correlation coefficient, and how do the data look:</p>
<pre class="r"><code>cor(rladies_tweets$favorite_count, rladies_tweets$retweet_count, method = &quot;spearman&quot;)</code></pre>
<pre><code>## [1] 0.5486673</code></pre>
<pre class="r"><code>ggplot(rladies_tweets) +
  geom_point(aes(retweet_count, favorite_count))</code></pre>
<p><img src="../../post/RLadies_tweets_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>There’s a slight positive orientation of data points, but no specific pattern. The correlation coefficient is 0.55, which means that there is a positive correlation, but it is not so strong.</p>
<p>What it actually means is that people who follow the @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> account tend to favorite tweets way more often than they tend to retweet them. I assume it’s because it is easier to just press the ❤️ button, instead of hitting “retweet” and then having to retweet as it is (with no extra info - maybe confusing to their followers) or having to write some description about a tweet they just happen to like. Liking a tweet is just easier than spreading the info about it. I can’t generalize these results, though, so I don’t know if this really happens for all accounts.</p>
</div>
<div id="whats-the-location-of-the-majority-of-tweets" class="section level2">
<h2>What’s the location of the majority of tweets?</h2>
<p>The function <code>get_timeline</code> that we used at the beginning only accesses tweets posted by the @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> account. In order to see all tweets related to the account, including mentions, replies, etc., we need to use <code>search_tweets</code>.</p>
<pre class="r"><code># find url of first tweet
tweet_url &lt;- &quot;https://twitter.com/rladies_iwd2018/status/971140001495908353&quot;
id &lt;- gsub(&quot;.*status/&quot;, &quot;&quot;, tweet_url)

tweets &lt;- search_tweets(
  q = &quot;@rladies_iwd2018 OR to:rladies_iwd2018 OR rladies_iwd2018&quot;,
  sinceId = id, n = 2000, include_rts = FALSE)

tweets &lt;- tweets %&gt;%
  distinct()

tweets &lt;- arrange(tweets, desc(created_at))</code></pre>
<p>Now, we can explore geographic locations of all tweets and replies:</p>
<pre class="r"><code>tweets %&gt;%
  subset(!is.na(country)) %&gt;%
  janitor::tabyl(country) %&gt;%
  arrange(desc(country))</code></pre>
<pre><code>##         country  n    percent
## 1       Uruguay 38 0.82608696
## 2 United States  4 0.08695652
## 3         India  2 0.04347826
## 4     Australia  2 0.04347826</code></pre>
<p>It looks like Uruguay🇺🇾 is ahead for a big margin! Does this mean that somebody in Uruguay🇺🇾 has won the game?</p>
<p>It looks like not everybody has their location services on, though. After all, only 5% of tweets mention their location.</p>
<p>Let’s try to find out who did in fact win the game!</p>
</div>
<div id="who-won-the-game" class="section level2">
<h2>Who won the game?</h2>
<p>In order to know who won the game, let’s take a look at all replies, by <code>user_id</code>:</p>
<pre class="r"><code>tweets %&gt;% 
  janitor::tabyl(user_id) %&gt;%
  arrange(desc(n)) %&gt;%
  head(10)</code></pre>
<pre><code>##               user_id   n    percent
## 1  957247055898046464 442 0.44736842
## 2           633700365 166 0.16801619
## 3           114258616  38 0.03846154
## 4          3367336625  35 0.03542510
## 5           776402106  33 0.03340081
## 6          2865404679  25 0.02530364
## 7            16284661  22 0.02226721
## 8           159846289  15 0.01518219
## 9            19429174  12 0.01214575
## 10           23622967  11 0.01113360</code></pre>
<p>So, the first place with <code>user_id = &quot;957247055898046464&quot;</code> is clearly the @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> account because there are 442. Let’s check:</p>
<pre class="r"><code>tweets %&gt;% 
  janitor::tabyl(user_id) %&gt;%
  arrange(desc(n)) %&gt;%
  filter(n == 442) %&gt;%
  lookup_users()</code></pre>
<pre><code>## # A tibble: 1 x 20
##   user_id  name    screen_name location description       url    protected
##   &lt;chr&gt;    &lt;chr&gt;   &lt;chr&gt;       &lt;chr&gt;    &lt;chr&gt;             &lt;chr&gt;  &lt;lgl&gt;    
## 1 9572470~ IWD 20~ rladies_iw~ The who~ Promoting gender~ https~ FALSE    
## # ... with 13 more variables: followers_count &lt;int&gt;, friends_count &lt;int&gt;,
## #   listed_count &lt;int&gt;, statuses_count &lt;int&gt;, favourites_count &lt;int&gt;,
## #   account_created_at &lt;dttm&gt;, verified &lt;lgl&gt;, profile_url &lt;chr&gt;,
## #   profile_expanded_url &lt;chr&gt;, account_lang &lt;chr&gt;,
## #   profile_banner_url &lt;lgl&gt;, profile_background_url &lt;chr&gt;,
## #   profile_image_url &lt;chr&gt;</code></pre>
<p>Indeed, that is the @<a href="http://www.twitter/rladies_iwd2018">rladies_iwd2018</a> account.</p>
<p>The second place is interesting, because it has 166 replies, which is a huge difference in comparison to the third place! Let’s find out who is this person!</p>
<p>And the winner is 🥁🥁🥁:</p>
<pre class="r"><code>tweets %&gt;% 
  janitor::tabyl(user_id) %&gt;%
  arrange(desc(n)) %&gt;%
  filter(n == 166) %&gt;%
  lookup_users()</code></pre>
<pre><code>## # A tibble: 1 x 20
##   user_id  name   screen_name location description         url   protected
##   &lt;chr&gt;    &lt;chr&gt;  &lt;chr&gt;       &lt;chr&gt;    &lt;chr&gt;               &lt;lgl&gt; &lt;lgl&gt;    
## 1 6337003~ Laura~ _lacion_    Buenos ~ Biostatistician/Da~ NA    FALSE    
## # ... with 13 more variables: followers_count &lt;int&gt;, friends_count &lt;int&gt;,
## #   listed_count &lt;int&gt;, statuses_count &lt;int&gt;, favourites_count &lt;int&gt;,
## #   account_created_at &lt;dttm&gt;, verified &lt;lgl&gt;, profile_url &lt;chr&gt;,
## #   profile_expanded_url &lt;chr&gt;, account_lang &lt;chr&gt;,
## #   profile_banner_url &lt;chr&gt;, profile_background_url &lt;chr&gt;,
## #   profile_image_url &lt;chr&gt;</code></pre>
<p>The winner of the game is <a href="https://twitter.com/_lacion_">Laura Acion</a>, with 166 replies!!!</p>
</div>
<div id="conclusions" class="section level2">
<h2>Conclusions</h2>
<p>With this analysis I’ve learned that:</p>
<ul>
<li>Tweets happened on 08.03.2018 - exactly as planned for iwd2018</li>
<li>People tend to favorite tweets, but not necessarily to retweet (correlation ~50%)</li>
<li>The majority of tweet replies come from Uruguay🇺🇾 (but there are a lot of missing locations)</li>
<li><a href="https://twitter.com/_lacion_">Laura Acion</a> won the game!</li>
</ul>
<div id="p.s.-how-does-the-largest-chain-of-tweets-and-replies-look-like" class="section level4">
<h4>P.S. How does the largest chain of tweets and replies look like?</h4>
<p>I will try to recreate <a href="https://twitter.com/LucyStats">Lucy D’Agostino McGowan’s</a> analysis for twitter trees, using the tweet that got the highest number of replies. This tweet is by <a href="https://twitter.com/_lacion_">Laura Acion</a>:</p>
<p><a href="https://twitter.com/rladies_iwd2018/status/971560433835565057"><img src="../../image/tweet_0.png" alt="Tweet referencing @_lacion_, which got 7 responses, and on which the following tree is based" /></a></p>
<pre class="r"><code># Grab the tweets
id &lt;- &quot;971560433835565057&quot;
diff &lt;- 1
while (diff != 0) {
  id_next &lt;- tweets %&gt;%
    filter(reply_to_status_id %in% id) %&gt;%
    pull(status_id)
  id_new &lt;- unique(c(id, id_next))
  diff &lt;- length(id_new) - length(id)
  id &lt;- id_new
}

all_replies &lt;- tweets %&gt;% 
  filter(reply_to_status_id %in% id)

# Pull the replyee and replier text
from_text &lt;- all_replies %&gt;%
  select(reply_to_status_id) %&gt;%
  left_join(all_replies, c(&quot;reply_to_status_id&quot; = &quot;status_id&quot;)) %&gt;%
  select(screen_name, text)

to_text &lt;- paste0(all_replies$screen_name, &quot;: &quot;, all_replies$text)
to_text &lt;- gsub(&quot;&#39;&quot;, &quot;`&quot;, to_text)
from_text &lt;- paste0(from_text$screen_name, &quot;: &quot;, from_text$text)
from_text &lt;- gsub(&quot;&#39;&quot;, &quot;`&quot;, from_text)

# Set the text for tweet_0.
tweet_0 &lt;- tweets$text[tweets$status_id == &quot;971560433835565057&quot;]

# Create the edges
edges &lt;- tibble::tibble(
  from = from_text,
  to = to_text
) %&gt;%
  mutate(from = ifelse(
    from == &quot;NA: NA&quot;,
    tweet_0,
    from)
  )

# Create the graph
graph &lt;- graph_from_data_frame(edges, directed = TRUE)
V(graph)$tooltip &lt;- V(graph)$name

set.seed(8318)
p &lt;- ggraph(graph, layout = &quot;nicely&quot;) + 
  geom_edge_link() + 
  geom_point_interactive(aes(x, y, color = &quot;red&quot;, alpha = 0.05, tooltip = tooltip)) +
  theme_void() + 
  theme(legend.position = &quot;none&quot;)
ggiraph(code = print(p),
        width_svg = 10,
        zoom_max = 4)</code></pre>
<div id="htmlwidget-1" style="width:672px;height:480px;" class="ggiraph html-widget"></div>
<script type="application/json" data-for="htmlwidget-1">{"x":{"html":"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" id=\"svg_1\" viewBox=\"0 0 720.00 360.00\">\n  <g>\n    <defs>\n      <clipPath id=\"cl1_0\">\n        <rect x=\"0.00\" y=\"360.00\" width=\"0.00\" height=\"360.00\"/>\n      <\/clipPath>\n    <\/defs>\n    <rect x=\"0.00\" y=\"0.00\" width=\"720.00\" height=\"360.00\" id=\"1\" clip-path=\"url(#cl1_0)\" fill=\"#FFFFFF\" fill-opacity=\"1\" stroke-width=\"0.75\" stroke=\"#FFFFFF\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <defs>\n      <clipPath id=\"cl1_1\">\n        <rect x=\"0.00\" y=\"0.00\" width=\"720.00\" height=\"360.00\"/>\n      <\/clipPath>\n    <\/defs>\n    <defs>\n      <clipPath id=\"cl1_2\">\n        <rect x=\"2.74\" y=\"0.00\" width=\"717.26\" height=\"357.26\"/>\n      <\/clipPath>\n    <\/defs>\n    <polyline points=\"350.95,182.63 350.52,180.95 350.10,179.27 349.67,177.59 349.24,175.91 348.81,174.23 348.38,172.55 347.96,170.87 347.53,169.19 347.10,167.50 346.67,165.82 346.25,164.14 345.82,162.46 345.39,160.78 344.96,159.10 344.54,157.42 344.11,155.74 343.68,154.06 343.25,152.38 342.82,150.70 342.40,149.02 341.97,147.34 341.54,145.66 341.11,143.97 340.69,142.29 340.26,140.61 339.83,138.93 339.40,137.25 338.97,135.57 338.55,133.89 338.12,132.21 337.69,130.53 337.26,128.85 336.84,127.17 336.41,125.49 335.98,123.81 335.55,122.13 335.12,120.44 334.70,118.76 334.27,117.08 333.84,115.40 333.41,113.72 332.99,112.04 332.56,110.36 332.13,108.68 331.70,107.00 331.27,105.32 330.85,103.64 330.42,101.96 329.99,100.28 329.56,98.59 329.14,96.91 328.71,95.23 328.28,93.55 327.85,91.87 327.42,90.19 327.00,88.51 326.57,86.83 326.14,85.15 325.71,83.47 325.29,81.79 324.86,80.11 324.43,78.43 324.00,76.75 323.57,75.06 323.15,73.38 322.72,71.70 322.29,70.02 321.86,68.34 321.44,66.66 321.01,64.98 320.58,63.30 320.15,61.62 319.72,59.94 319.30,58.26 318.87,56.58 318.44,54.90 318.01,53.22 317.59,51.53 317.16,49.85 316.73,48.17 316.30,46.49 315.87,44.81 315.45,43.13 315.02,41.45 314.59,39.77 314.16,38.09 313.74,36.41 313.31,34.73 312.88,33.05 312.45,31.37 312.02,29.68 311.60,28.00 311.17,26.32 310.74,24.64 310.31,22.96 309.89,21.28 309.46,19.60 309.03,17.92 308.60,16.24\" id=\"2\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <polyline points=\"350.95,182.63 347.76,183.21 344.58,183.78 341.39,184.36 338.20,184.94 335.01,185.51 331.82,186.09 328.64,186.66 325.45,187.24 322.26,187.82 319.07,188.39 315.88,188.97 312.70,189.54 309.51,190.12 306.32,190.70 303.13,191.27 299.94,191.85 296.76,192.42 293.57,193.00 290.38,193.58 287.19,194.15 284.00,194.73 280.82,195.30 277.63,195.88 274.44,196.45 271.25,197.03 268.06,197.61 264.88,198.18 261.69,198.76 258.50,199.33 255.31,199.91 252.12,200.49 248.94,201.06 245.75,201.64 242.56,202.21 239.37,202.79 236.18,203.37 233.00,203.94 229.81,204.52 226.62,205.09 223.43,205.67 220.24,206.25 217.06,206.82 213.87,207.40 210.68,207.97 207.49,208.55 204.30,209.13 201.12,209.70 197.93,210.28 194.74,210.85 191.55,211.43 188.37,212.01 185.18,212.58 181.99,213.16 178.80,213.73 175.61,214.31 172.43,214.89 169.24,215.46 166.05,216.04 162.86,216.61 159.67,217.19 156.49,217.77 153.30,218.34 150.11,218.92 146.92,219.49 143.73,220.07 140.55,220.65 137.36,221.22 134.17,221.80 130.98,222.37 127.79,222.95 124.61,223.53 121.42,224.10 118.23,224.68 115.04,225.25 111.85,225.83 108.67,226.41 105.48,226.98 102.29,227.56 99.10,228.13 95.91,228.71 92.73,229.29 89.54,229.86 86.35,230.44 83.16,231.01 79.97,231.59 76.79,232.17 73.60,232.74 70.41,233.32 67.22,233.89 64.03,234.47 60.85,235.05 57.66,235.62 54.47,236.20 51.28,236.77 48.09,237.35 44.91,237.93 41.72,238.50 38.53,239.08 35.34,239.65\" id=\"3\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <polyline points=\"350.95,182.63 353.31,181.42 355.68,180.21 358.04,179.00 360.40,177.78 362.76,176.57 365.12,175.36 367.48,174.15 369.85,172.94 372.21,171.72 374.57,170.51 376.93,169.30 379.29,168.09 381.66,166.88 384.02,165.67 386.38,164.45 388.74,163.24 391.10,162.03 393.47,160.82 395.83,159.61 398.19,158.39 400.55,157.18 402.91,155.97 405.27,154.76 407.64,153.55 410.00,152.34 412.36,151.12 414.72,149.91 417.08,148.70 419.45,147.49 421.81,146.28 424.17,145.06 426.53,143.85 428.89,142.64 431.26,141.43 433.62,140.22 435.98,139.00 438.34,137.79 440.70,136.58 443.06,135.37 445.43,134.16 447.79,132.95 450.15,131.73 452.51,130.52 454.87,129.31 457.24,128.10 459.60,126.89 461.96,125.67 464.32,124.46 466.68,123.25 469.05,122.04 471.41,120.83 473.77,119.62 476.13,118.40 478.49,117.19 480.86,115.98 483.22,114.77 485.58,113.56 487.94,112.34 490.30,111.13 492.66,109.92 495.03,108.71 497.39,107.50 499.75,106.29 502.11,105.07 504.47,103.86 506.84,102.65 509.20,101.44 511.56,100.23 513.92,99.01 516.28,97.80 518.65,96.59 521.01,95.38 523.37,94.17 525.73,92.95 528.09,91.74 530.45,90.53 532.82,89.32 535.18,88.11 537.54,86.90 539.90,85.68 542.26,84.47 544.63,83.26 546.99,82.05 549.35,80.84 551.71,79.62 554.07,78.41 556.44,77.20 558.80,75.99 561.16,74.78 563.52,73.57 565.88,72.35 568.24,71.14 570.61,69.93 572.97,68.72 575.33,67.51 577.69,66.29 580.05,65.08 582.42,63.87 584.78,62.66\" id=\"4\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <polyline points=\"350.95,182.63 348.04,181.75 345.13,180.87 342.22,179.99 339.31,179.11 336.40,178.23 333.49,177.35 330.58,176.48 327.67,175.60 324.76,174.72 321.85,173.84 318.93,172.96 316.02,172.08 313.11,171.20 310.20,170.32 307.29,169.44 304.38,168.56 301.47,167.68 298.56,166.80 295.65,165.92 292.74,165.04 289.83,164.16 286.92,163.28 284.01,162.40 281.10,161.52 278.19,160.65 275.28,159.77 272.36,158.89 269.45,158.01 266.54,157.13 263.63,156.25 260.72,155.37 257.81,154.49 254.90,153.61 251.99,152.73 249.08,151.85 246.17,150.97 243.26,150.09 240.35,149.21 237.44,148.33 234.53,147.45 231.62,146.57 228.71,145.69 225.79,144.82 222.88,143.94 219.97,143.06 217.06,142.18 214.15,141.30 211.24,140.42 208.33,139.54 205.42,138.66 202.51,137.78 199.60,136.90 196.69,136.02 193.78,135.14 190.87,134.26 187.96,133.38 185.05,132.50 182.14,131.62 179.23,130.74 176.31,129.86 173.40,128.99 170.49,128.11 167.58,127.23 164.67,126.35 161.76,125.47 158.85,124.59 155.94,123.71 153.03,122.83 150.12,121.95 147.21,121.07 144.30,120.19 141.39,119.31 138.48,118.43 135.57,117.55 132.66,116.67 129.74,115.79 126.83,114.91 123.92,114.04 121.01,113.16 118.10,112.28 115.19,111.40 112.28,110.52 109.37,109.64 106.46,108.76 103.55,107.88 100.64,107.00 97.73,106.12 94.82,105.24 91.91,104.36 89.00,103.48 86.09,102.60 83.17,101.72 80.26,100.84 77.35,99.96 74.44,99.08 71.53,98.21 68.62,97.33 65.71,96.45 62.80,95.57\" id=\"5\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <polyline points=\"350.95,182.63 349.88,184.23 348.81,185.83 347.74,187.43 346.67,189.03 345.60,190.63 344.52,192.23 343.45,193.83 342.38,195.43 341.31,197.03 340.24,198.63 339.17,200.23 338.10,201.83 337.03,203.43 335.95,205.03 334.88,206.63 333.81,208.23 332.74,209.83 331.67,211.43 330.60,213.03 329.53,214.63 328.46,216.23 327.38,217.83 326.31,219.43 325.24,221.03 324.17,222.63 323.10,224.23 322.03,225.83 320.96,227.43 319.89,229.03 318.81,230.63 317.74,232.23 316.67,233.83 315.60,235.43 314.53,237.03 313.46,238.63 312.39,240.23 311.32,241.83 310.25,243.43 309.17,245.03 308.10,246.63 307.03,248.23 305.96,249.83 304.89,251.43 303.82,253.03 302.75,254.63 301.68,256.23 300.60,257.83 299.53,259.43 298.46,261.03 297.39,262.63 296.32,264.23 295.25,265.83 294.18,267.43 293.11,269.03 292.03,270.63 290.96,272.23 289.89,273.83 288.82,275.43 287.75,277.03 286.68,278.63 285.61,280.23 284.54,281.82 283.46,283.42 282.39,285.02 281.32,286.62 280.25,288.22 279.18,289.82 278.11,291.42 277.04,293.02 275.97,294.62 274.89,296.22 273.82,297.82 272.75,299.42 271.68,301.02 270.61,302.62 269.54,304.22 268.47,305.82 267.40,307.42 266.33,309.02 265.25,310.62 264.18,312.22 263.11,313.82 262.04,315.42 260.97,317.02 259.90,318.62 258.83,320.22 257.76,321.82 256.68,323.42 255.61,325.02 254.54,326.62 253.47,328.22 252.40,329.82 251.33,331.42 250.26,333.02 249.19,334.62 248.11,336.22 247.04,337.82 245.97,339.42 244.90,341.02\" id=\"6\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <polyline points=\"350.95,182.63 352.83,184.04 354.70,185.45 356.57,186.86 358.45,188.27 360.32,189.68 362.20,191.09 364.07,192.50 365.94,193.91 367.82,195.32 369.69,196.73 371.57,198.14 373.44,199.55 375.32,200.96 377.19,202.37 379.06,203.78 380.94,205.19 382.81,206.60 384.69,208.01 386.56,209.42 388.43,210.83 390.31,212.25 392.18,213.66 394.06,215.07 395.93,216.48 397.81,217.89 399.68,219.30 401.55,220.71 403.43,222.12 405.30,223.53 407.18,224.94 409.05,226.35 410.92,227.76 412.80,229.17 414.67,230.58 416.55,231.99 418.42,233.40 420.30,234.81 422.17,236.22 424.04,237.63 425.92,239.04 427.79,240.45 429.67,241.86 431.54,243.27 433.41,244.68 435.29,246.09 437.16,247.50 439.04,248.91 440.91,250.32 442.79,251.73 444.66,253.14 446.53,254.55 448.41,255.96 450.28,257.37 452.16,258.78 454.03,260.19 455.90,261.60 457.78,263.01 459.65,264.42 461.53,265.83 463.40,267.24 465.28,268.65 467.15,270.06 469.02,271.47 470.90,272.88 472.77,274.29 474.65,275.70 476.52,277.11 478.39,278.52 480.27,279.93 482.14,281.34 484.02,282.75 485.89,284.16 487.77,285.57 489.64,286.98 491.51,288.39 493.39,289.80 495.26,291.22 497.14,292.63 499.01,294.04 500.88,295.45 502.76,296.86 504.63,298.27 506.51,299.68 508.38,301.09 510.25,302.50 512.13,303.91 514.00,305.32 515.88,306.73 517.75,308.14 519.63,309.55 521.50,310.96 523.37,312.37 525.25,313.78 527.12,315.19 529.00,316.60 530.87,318.01 532.74,319.42 534.62,320.83 536.49,322.24\" id=\"7\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <polyline points=\"350.95,182.63 354.35,182.78 357.75,182.93 361.15,183.08 364.55,183.24 367.94,183.39 371.34,183.54 374.74,183.69 378.14,183.84 381.54,183.99 384.94,184.14 388.33,184.29 391.73,184.45 395.13,184.60 398.53,184.75 401.93,184.90 405.33,185.05 408.73,185.20 412.12,185.35 415.52,185.50 418.92,185.66 422.32,185.81 425.72,185.96 429.12,186.11 432.51,186.26 435.91,186.41 439.31,186.56 442.71,186.71 446.11,186.87 449.51,187.02 452.90,187.17 456.30,187.32 459.70,187.47 463.10,187.62 466.50,187.77 469.90,187.92 473.30,188.08 476.69,188.23 480.09,188.38 483.49,188.53 486.89,188.68 490.29,188.83 493.69,188.98 497.08,189.13 500.48,189.29 503.88,189.44 507.28,189.59 510.68,189.74 514.08,189.89 517.48,190.04 520.87,190.19 524.27,190.34 527.67,190.50 531.07,190.65 534.47,190.80 537.87,190.95 541.26,191.10 544.66,191.25 548.06,191.40 551.46,191.55 554.86,191.71 558.26,191.86 561.65,192.01 565.05,192.16 568.45,192.31 571.85,192.46 575.25,192.61 578.65,192.76 582.05,192.92 585.44,193.07 588.84,193.22 592.24,193.37 595.64,193.52 599.04,193.67 602.44,193.82 605.83,193.97 609.23,194.13 612.63,194.28 616.03,194.43 619.43,194.58 622.83,194.73 626.23,194.88 629.62,195.03 633.02,195.18 636.42,195.34 639.82,195.49 643.22,195.64 646.62,195.79 650.01,195.94 653.41,196.09 656.81,196.24 660.21,196.39 663.61,196.55 667.01,196.70 670.41,196.85 673.80,197.00 677.20,197.15 680.60,197.30 684.00,197.45 687.40,197.60\" id=\"8\" clip-path=\"url(#cl1_2)\" fill=\"none\" stroke-width=\"1.06698\" stroke=\"#000000\" stroke-opacity=\"1\" stroke-linejoin=\"round\" stroke-linecap=\"butt\"/>\n    <circle cx=\"350.95\" cy=\"182.63\" r=\"1.47pt\" id=\"9\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"308.60\" cy=\"16.24\" r=\"1.47pt\" id=\"10\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"35.34\" cy=\"239.65\" r=\"1.47pt\" id=\"11\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"584.78\" cy=\"62.66\" r=\"1.47pt\" id=\"12\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"62.80\" cy=\"95.57\" r=\"1.47pt\" id=\"13\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"244.90\" cy=\"341.02\" r=\"1.47pt\" id=\"14\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"536.49\" cy=\"322.24\" r=\"1.47pt\" id=\"15\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <circle cx=\"687.40\" cy=\"197.60\" r=\"1.47pt\" id=\"16\" clip-path=\"url(#cl1_2)\" fill=\"#F8766D\" fill-opacity=\"0.55\" stroke-width=\"0.708661\" stroke=\"#F8766D\" stroke-opacity=\"0.55\" stroke-linejoin=\"round\" stroke-linecap=\"round\"/>\n    <defs>\n      <clipPath id=\"cl1_3\">\n        <rect x=\"0.00\" y=\"0.00\" width=\"720.00\" height=\"360.00\"/>\n      <\/clipPath>\n    <\/defs>\n  <\/g>\n<\/svg>\n","css":".tooltip_svg_1 {position:absolute;pointer-events:none;z-index:999;padding:5px;background:black;color:white;border-radius:2px 2px 2px 2px;}\n.cl_data_id_svg_1:{}.cl_data_id_svg_1:hover{fill:orange;stroke:gray;}\n.clicked_svg_1{fill:orange;stroke:gray;}","ui_html":"<div class='ggiraph-toolbar'><div class='ggiraph-toolbar-block shinyonly'><a class='ggiraph-toolbar-icon neutral' title='lasso selection' href='javascript:lasso_on(\"svg_1\", true, \"array_selected_svg_1\", \"clicked_svg_1\");'><svg width='15pt' height='15pt' viewBox='0 0 230 230'><g><ellipse ry='65.5' rx='86.5' cy='94' cx='115.5' stroke-width='20' fill='transparent'/><ellipse ry='11.500001' rx='10.5' cy='153' cx='91.5' stroke-width='20' fill='transparent'/><line y2='210.5' x2='105' y1='164.5' x1='96' stroke-width='20'/><\/g><\/svg><\/a><a class='ggiraph-toolbar-icon drop' title='lasso anti-selection' href='javascript:lasso_on(\"svg_1\", false, \"array_selected_svg_1\", \"clicked_svg_1\");'><svg width='15pt' height='15pt' viewBox='0 0 230 230'><g><ellipse ry='65.5' rx='86.5' cy='94' cx='115.5' stroke-width='20' fill='transparent'/><ellipse ry='11.500001' rx='10.5' cy='153' cx='91.5' stroke-width='20' fill='transparent'/><line y2='210.5' x2='105' y1='164.5' x1='96' stroke-width='20'/><\/g><\/svg><\/a><\/div><div class='ggiraph-toolbar-block'><a class='ggiraph-toolbar-icon neutral' title='pan-zoom reset' href='javascript:zoom_identity_ggiraph(\"svg_1\", zoom_svg_1);'><svg width='15pt' height='15pt' viewBox='0 0 512 512'><g><polygon points='274,209.7 337.9,145.9 288,96 416,96 416,224 366.1,174.1 302.3,238 '/><polygon points='274,302.3 337.9,366.1 288,416 416,416 416,288 366.1,337.9 302.3,274'/><polygon points='238,302.3 174.1,366.1 224,416 96,416 96,288 145.9,337.9 209.7,274'/><polygon points='238,209.7 174.1,145.9 224,96 96,96 96,224 145.9,174.1 209.7,238'/><\/g><svg><\/a><a class='ggiraph-toolbar-icon neutral' title='activate pan-zoom' href='javascript:zoom_on_ggiraph(\"svg_1\", zoom_svg_1);'><svg width='15pt' height='15pt' viewBox='0 0 512 512'><g><ellipse ry='150' rx='150' cy='213' cx='203.5' stroke-width='50' fill='transparent'/><line y2='455.5' x2='416' y1='331.5' x1='301' stroke-width='50'/><\/g><\/svg><\/a><a class='ggiraph-toolbar-icon neutral' title='desactivate pan-zoom' href='javascript:zoom_off_ggiraph(\"svg_1\", zoom_svg_1);'><svg width='15pt' height='15pt' viewBox='0 0 512 512'><g><ellipse ry='150' rx='150' cy='213' cx='203.5' stroke-width='50' fill='transparent'/><line y2='455.5' x2='416' y1='331.5' x1='301' stroke-width='50'/><line y2='455' x2='0' y1='0' x1='416' stroke-width='30'/><\/g><\/svg><\/a><\/div><\/div>","uid":"svg_1","width":"75%","funname":"init_prop_svg_1","sel_array_name":"array_selected_svg_1","selected_class":"clicked_svg_1","tooltip_opacity":0.9,"tooltip_offx":10,"tooltip_offy":0,"zoom_max":4,"selection_type":"multiple"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</div>

    
    

    

    

</main>

        <footer>

            <p class="copyright text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io">Hugo</a> and <a href="https://github.com/calintat/minimal">Minimal</a></p>

        </footer>
       
    </body>

</html>

