name: Initiate chapter.json
on:
  issues:
    types: [opened]

jobs:
  new-chapter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Print issue inputs
        env:
          INPUTS: ${{ toJson(github.event.issue.inputs) }}
        run: |
          echo "Issue inputs: $INPUTS"
          nested_inputs=$(echo $INPUTS | jq '.["nested-subinputs"].children')
          echo "Nested inputs: $nested_inputs"

