name: Validate jsons

on:
  push:
  pull_request:
    branches:
      - main
      - fork_merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  jsons:
    env:
      RENV_PROFILE: "json"
      RENV_CONFIG_SANDBOX_ENABLED: FALSE
    name: Check modified jsons
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev
        
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.0'

      - name: Setup Renv
        uses: r-lib/actions/setup-renv@v2
      
      - name: Validate jsons
        run: Rscript scripts/validate_jsons.R
