name: PR Checklist for Content Changes

on:
  pull_request_target:
    types: [opened]
    paths:
      - "content/{blog,news}/**/index*.{md,qmd,rmd}"

permissions:
  contents: read
  packages: read

jobs:
  checklist:
    uses: rladies/jinx/.github/workflows/reusable-post-checklist.yml@main
    secrets:
      JINX_APP_ID: ${{ secrets.JINX_APP_ID }}
      JINX_PRIVATE_KEY: ${{ secrets.JINX_PRIVATE_KEY }}
