name: Validate jsons
name: Validate jsons

on:
  push:
  pull_request:
    branches:
      - main
      - fork_merge

jobs:
  jsons:
    name: Check modified jsons
    runs-on: macOS-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get changed files
        id: check_files
        run: |
          git diff-tree --no-commit-id --name-only -r ${{ github.sha }}~10..${{ github.sha }} | grep "^data/"
          echo "{run_validation}={$(grep -c "^data/" $GITHUB_WORKSPACE/.git/FETCH_HEAD)}" >> $GITHUB_ENV

      - name: Setup R
        if: env.run_validation != '0'
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache packages
        if: env.run_validation != '0'
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        if: env.run_validation != '0'
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        
      - name: Install R-packages
        if: env.run_validation != '0'
        run: install.packages(c("here", "jsonvalidate"), Ncpus = 2)
        shell: Rscript {0}
      
      - name: Validate jsons
        if: env.run_validation != '0'
        run: Rscript scripts/validate_jsons.R
