name: "Check production build"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Production build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set env parameters
        run: |
          ver=$(cat .hugoversion)
          echo "hugovr=$ver" >> $GITHUB_ENV

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.hugovr }}
          extended: true

      - name: Build
        run: |
          hugo \
            -e production \
            -d public
