name: Validate jsons

on:
  push:
  pull_request:
    branches:
      - main
      - fork_merge

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  jsons:
    name: Check modified jsons
    runs-on: macOS-latest
    env:
      RENV_PATHS_ROOT: ~/.local/share/renv
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.0'

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
      
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        
      - name: Install R-packages
        run: install.packages(c("here", "jsonvalidate"), Ncpus = 2)
        shell: Rscript {0}
      
      - name: Validate jsons
        run: Rscript scripts/validate_jsons.R
