name: Get Global Team from Airtable

on:
  schedule:
    - cron: "16 16 * * 0"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RENV_PROFILE: "airtable"
  RENV_CONFIG_SANDBOX_ENABLED: FALSE

jobs:
  airtable:
    name: Retrieve Airtable data
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.JINX_APP_ID }}
          private-key: ${{ secrets.JINX_PRIVATE_KEY }}
          owner: rladies

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Install cURL Headers
        run: |
          sudo apt-get update
          sudo apt-get install libcurl4-openssl-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "renv"

      - name: Setup Renv
        uses: r-lib/actions/setup-renv@v2

      - name: Get Airtable data and write to file
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        run: Rscript scripts/get_global_team.R

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ steps.app-token.outputs.token }}
          add-paths: |
            content/about-us/global-team/img
            data/global_team
          commit-message: "Automated update: Update Global Team"
          branch: automated/global-team-update
          title: "Automated update: Update Global Team"
          body: "Weekly automated update of Global Team data from Airtable."
          labels: automated
